# Generated by Django 3.1.6 on 2021-03-02 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('statuscontroller', '0003_auto_20210301_0943'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default='', max_length=50, verbose_name='包全名')),
                ('version', models.CharField(default='', max_length=50, verbose_name='版本名')),
                ('test_tool', models.CharField(default='', max_length=50, verbose_name='测试工具')),
                ('language', models.CharField(default='', max_length=10, verbose_name='语言')),
                ('description', models.TextField(default='', verbose_name='包描述')),
                ('start_time', models.DateTimeField(auto_now=True, verbose_name='开始时间')),
                ('time', models.DateTimeField(auto_now=True, verbose_name='运行时长')),
                ('end_time', models.DateTimeField(auto_now=True, verbose_name='结束时间')),
                ('analysis_status', models.IntegerField(choices=[(1, '未开始'), (2, '正在分析'), (3, '已完成')], verbose_name='分析状态')),
                ('result_description', models.TextField(default='', verbose_name='结果文件介绍')),
                ('target_paoject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='statuscontroller.projects', verbose_name='对应项目')),
            ],
        ),
    ]
