# Generated by Django 3.1.6 on 2021-03-02 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packageinfo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='package',
            old_name='target_paoject',
            new_name='target_project',
        ),
    ]
