# Generated by Django 3.1.6 on 2021-03-01 01:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100, verbose_name='项目全名')),
                ('host_id', models.CharField(default='', max_length=100, verbose_name='主机ID')),
                ('host_ip', models.GenericIPAddressField(default='0.0.0.0', verbose_name='主机IP地址')),
                ('OS', models.CharField(default='', max_length=50, verbose_name='操作系统')),
                ('description', models.TextField(default='', verbose_name='项目描述')),
                ('start_time', models.DateTimeField(auto_now=True, verbose_name='开始时间')),
                ('time', models.DateTimeField(auto_now=True, verbose_name='运行时长')),
                ('end_time', models.DateTimeField(auto_now=True, verbose_name='结束时间')),
                ('analysis_status', models.CharField(choices=[(1, '未开始'), (2, '正在分析'), (3, '已完成')], max_length=20, verbose_name='分析状态')),
                ('result_description', models.TextField(default='', verbose_name='结果文件介绍')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='所有者')),
            ],
        ),
    ]
