# Generated by Django 3.1.6 on 2021-03-01 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statuscontroller', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='analysis_status',
            field=models.IntegerField(choices=[(1, '未开始'), (2, '正在分析'), (3, '已完成')], max_length=20, verbose_name='分析状态'),
        ),
    ]
